using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class InventoryUI : MonoBehaviour
{
    public Sprite dirtSprite;
    public Sprite grassSprite;
    public Sprite waterSprite;

    public List<Transform> Slot = new List<Transform>();
    public GameObject SlotItem;
    List<GameObject> items = new List<GameObject>();

    public int selectedIndex = -1;
   public void UpdateInventory(Inventory myInven)
   {
        foreach(var slotItems in items)
        {
            Destroy(slotItems);
        }
        items.Clear();

        int idx = 0;
        foreach(var item in myInven.items)
        {
            var go = Instantiate(SlotItem, Slot[idx].transform);
            go.transform.localPosition = Vector3.zero;
            SlotItemPrefab sItem = go.GetComponent<SlotItemPrefab>();
            items.Add(go);

            switch(item.Key)
            {
                case BlockType.Dirt:
                    sItem.ItemSetting(dirtSprite, "x" + item.Value.ToString(), item.Key);
                    break;
                case BlockType.Grass:
                    sItem.ItemSetting(grassSprite, "x" + item.Value.ToString(), item.Key);
                    break;
                case BlockType.Water:
                    sItem.ItemSetting(waterSprite, "x" + item.Value.ToString(), item.Key);
                    break;
            }
            idx++;
        }
   }
    private void Update()
    {
      for (int i = 0; i< Mathf.Min(9, Slot.Count); i++)
            if(Input.GetKeyDown(KeyCode.Alpha1+i))
            {
                SetselectedIndex(i);
            }
    }
    public void SetselectedIndex(int idx)
    {
        Resetselection();
        if (selectedIndex == idx)
        {
            selectedIndex = -1;
        }
        else
        {
            Setselection(idx);
            selectedIndex = idx;
        }
    }
    public void Resetselection()
    {
        foreach(var slot in Slot)
        {
            slot.GetComponent<Image>().color = Color.white;
        }
    }
    void Setselection(int _idx)
    {
        Slot[_idx].GetComponent<Image>().color = Color.yellow;
    }
    public BlockType GetInventoryslot()
    {
        return items[selectedIndex].GetComponent<SlotItemPrefab>().blockType;
    }
}
